# Generated by Django 4.1 on 2022-08-20 05:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e238eded-606a-405f-88ef-a8bcee7f434c'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
