# Generated by Django 4.1 on 2022-08-23 11:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('22a8d64f-3971-41e2-9a07-1bd6e75a0518'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
