# Generated by Django 4.1 on 2022-08-23 16:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('413bc43a-0bee-4da0-84bd-4bfc4d967ec1'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
