# Generated by Django 4.1 on 2022-08-24 09:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4b16bbf1-dcc2-4785-bcb2-fc98ef89f66a'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
