# Generated by Django 4.1 on 2022-08-24 09:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5a66f226-4c8b-44de-a89d-8af6f1787d92'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
