# Generated by Django 4.1 on 2022-08-24 09:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_bookinstance_borrowed_alter_bookinstance_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='borrowed',
            new_name='borrower',
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('46738656-895e-4719-b4e6-55befe819f7a'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
