# Generated by Django 4.1 on 2022-08-24 10:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_rename_borrowed_bookinstance_borrower_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set books as returned'),)},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6addade1-8ae7-476f-ace9-b7315e2209b7'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
